drop table if exists item CASCADE;
create table item
(
    id        bigint generated by default as identity,
    item_name varchar(10),
    price     integer,
    quantity  integer,
    primary key (id)
);

-- 등록 쿼리
insert into item(item_name, pricem, quantity) values ('ItemTest', 10000, 10);
-- 조회 쿼리
select * from item;